#!/bin/sh

RELEASE_TAG="$1"

if [ "$RELEASE_TAG" == "" ]; then
    echo "release version is missing!"
    echo "Usage:"
    echo "    ./unrelease v0.2.0"
    exit 1
fi


git tag -d "$RELEASE_TAG"
git push origin ":refs/tags/$RELEASE_TAG"